version: "3.7"

services:
  squirrel-mongo:
    image: mongo:latest
    command: mongod --bind_ip 0.0.0.0
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=squirrel"
      - "MONGO_INITDB_ROOT_PASSWORD=${SQUIRREL_MONGO_PASSWORD}"
    networks:
      - traefik
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: squirrel-mongo
        target: /data/db

  squirrel:
    build: .
    environment:
      - "MONGO_URI=mongodb://streamdata:${BLASEBALL_STREAMDATA_MONGO_PW}@squirrel-mongo"
    networks:
      - traefik

networks:
  squirrel:
    name: squirrel
    driver: bridge

volumes:
  squirrel-mongo:
